os:
   - linux
   - osx
language: rust
before_script:
   - rustup component add rustfmt
   - rustup component add clippy
rust:
   - stable
   - beta
   - nightly
script:
   - cargo test --all
   - cargo clippy --all-targets --all-features -- -D warnings
   - cargo fmt --all -- --check

before_deploy:
   - cargo build --release
   - cargo doc --no-deps
   - echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2 | tr '-' '_'`/index.html>" > target/doc/index.html


deploy:
   provider: pages
   local_dir: target/doc
   token: $GITHUB_OAUTH_TOKEN
   skip_cleanup: true
   keep_history: true
   on:
      branch: master
      rust: stable
      tags: true
      condition: $TRAVIS_OS_NAME == "linux"
