language: rust
before_script:
   - rustup component add rustfmt
   - rustup component add clippy
rust:
   - stable
   - beta
   - nightly
script:
   - cargo clippy --all-targets --all-features -- -D warnings
   - cargo fmt --all -- --check
deploy:
   provider: releases
   api_key: $GITHUB_OAUTH_TOKEN
   skip_cleanup: true
   on:
      tags: true