language: rust
before_script:
   - rustup component add rustfmt
   - rustup component add clippy
rust:
   - stable
script:
   - cargo test --all
   - cargo clippy --all-targets --all-features -- -D warnings
   - cargo fmt --all -- --check

before_deploy:
   - cargo build --release

deploy:
   provider: releases
   api_key: $GITHUB_OAUTH_TOKEN
   file: "target/release/bt"
   skip_cleanup: true
   on:
      branch: master
      tags: true
      rust: stable